### PR TITLE
Add link to Kiwi TCMS in tools

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by jaccz** [comment]
@atodorov , I'm trying to see how Kiwi TCMS relates to pairwise. I'm looking at the docs but can't find much about combinatorial testing features. I'm probably not looking in the right place. Do you have a pointer to any Kiwi docs that explain that part of its functionality? Thanks for the contribution!

**Comment by atodorov** [comment]
> @atodorov , I'm trying to see how Kiwi TCMS relates to pairwise. I'm looking at the docs but can't find much about combinatorial testing features. I'm probably not looking in the right place. 

I didn't expect you to be so quick. The docs are WIP and the functionality hasn't been deployed on the demo website. It will be in a few days. I can ping this PR once it is live.

**Comment by jaccz** [comment]
> I didn't expect you to be so quick. The docs are WIP and the functionality hasn't been deployed on the demo website. It will be in a few days. I can ping this PR once it is live.

:) Let me know when you're ready and I'll merge the PR.

**Comment by atodorov** [comment]
> Let me know when you're ready and I'll merge the PR.

https://kiwitcms.org/blog/atodorov/2022/01/24/properties-environments-and-test-matrix-generation/ contains a good explanation of how the test generation feature works (in combination with other features) and has screenshots at the bottom of the page. This functionality is also now live in case you want to play with it.

**Comment by jaccz** [comment]
> screenshots at the bottom of the page. This functionality is also now live in case you want to play with it.

Nice! Thanks.

**Pull request merged**
